GET http://localhost:8080
###

GET http://localhost:8080/catalogue
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6IlNhbWFudGhhIiwiZW1haWwiOiJzYW1hbnRoYUBhaXJ3ZWIuZnIiLCJhdXRoZW50aWNhdGVkIjp0cnVlLCJpYXQiOjE2NjI0OTY1NTgsImV4cCI6MTY2MjQ5NzQ1OH0.ExAMwK6zeuggoXbimRdBDgebMfz_KYMh-5zM4i_pkv4
####

GET http://localhost:8080/panier
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6IlNhbWFudGhhIiwiZW1haWwiOiJzYW1hbnRoYUBhaXJ3ZWIuZnIiLCJhdXRoZW50aWNhdGVkIjp0cnVlLCJpYXQiOjE2NjI0OTQ3NzksImV4cCI6MTY2MjQ5NTY3OX0.ALnsxARxSuGmFiaKMRGhTI0HKZV8ev1FjiQdY8Oe1pE
####

POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "samantha@airweb.fr",
  "password": "3bonjour"
}
####

PUT http://localhost:8080/panier
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6IlNhbWFudGhhIiwiZW1haWwiOiJzYW1hbnRoYUBhaXJ3ZWIuZnIiLCJhdXRoZW50aWNhdGVkIjp0cnVlLCJpYXQiOjE2NjI0OTY1NTgsImV4cCI6MTY2MjQ5NzQ1OH0.ExAMwK6zeuggoXbimRdBDgebMfz_KYMh-5zM4i_pkv4
Content-Type: application/json

{
  "productId": 4,
  "quantity": 1
}