GET http://localhost:8080/api/v1
###

GET http://localhost:8080/api/v1/catalogue
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6IlNhbWFudGhhIiwiZW1haWwiOiJzYW1hbnRoYUBhaXJ3ZWIuZnIiLCJhdXRoZW50aWNhdGVkIjp0cnVlLCJpYXQiOjE2NjI1NDIyMzQsImV4cCI6MTY2MjYwMjIzNH0.L_MRgoPgOC7NW38YigjVTJbpDd8lAi9z5OmKcxf4hmo
####

GET http://localhost:8080/api/v1/panier
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6IlNhbWFudGhhIiwiZW1haWwiOiJzYW1hbnRoYUBhaXJ3ZWIuZnIiLCJhdXRoZW50aWNhdGVkIjp0cnVlLCJpYXQiOjE2NjI1NDIyMzQsImV4cCI6MTY2MjYwMjIzNH0.L_MRgoPgOC7NW38YigjVTJbpDd8lAi9z5OmKcxf4hmo
####

POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "email": "samantha@airweb.fr",
  "password": "3bonjour"
}
####

PUT http://localhost:8080/api/v1/panier
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6IlNhbWFudGhhIiwiZW1haWwiOiJzYW1hbnRoYUBhaXJ3ZWIuZnIiLCJhdXRoZW50aWNhdGVkIjp0cnVlLCJpYXQiOjE2NjI1NDIyMzQsImV4cCI6MTY2MjYwMjIzNH0.L_MRgoPgOC7NW38YigjVTJbpDd8lAi9z5OmKcxf4hmo
Content-Type: application/json

{
  "productId": 4,
  "quantity": 1
}